hablapps/doric

src/main/scala/habla/doric/syntax/ArrayColumnOps.scala

This contribution supplies an alternative approach to deal with array-based operations, namely:
* `transform`
* `transformWithIndex`
* `aggregate`
* `filter`
Essentially, we exploit the expression API to get safer and more concise implementations.
Since this is my very first contribution to *doric*, supplying this link is a must (I'm sorry): https://www.youtube.com/watch?v=Y18jIMMNoHA

Alternative approach for ArrayColumn operations

---

src/main/scala/habla/doric/syntax/CommonColumnOps.scala
src/test/scala/habla/doric/syntax/AsSpec.scala

Closes #14 
Implemented `asDoric`, because as the method is already implemented in spark columns 😢

Implemented asDoric method

---

core/src/main/scala/doric/syntax/NumericColumns.scala
core/src/test/scala/doric/syntax/NumericOperationsSpec.scala

* Testing for Double NumericColumns

* Added division and mod operations for NumericColumns

---

.github/workflows/ci.yml
.github/workflows/publishTempSite.yml

After merging this PR:
1. affected worfklows will be available to be triggered manually at any branch
2. only `doc` branches will publish at gh-pages

ci: add worflow_dispatch

---

.github/workflows/release.yml

Release workflow will execute anyway, but the `publish` step will not execute

ci: release executed only if habla repository

---

.github/workflows/ci.yml
.github/workflows/publishTempSite.yml
.github/workflows/release.yml

A concurrency will be added to GitHub actions to avoid multiple jobs to run the same workflow:
https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
This change will affect:
* **CI** -> if two workflows are executing, first will be killed and the last one will run
* **publish** -> if two workflows are executing, first will be killed and the last one will run
* **release** -> sequential execution.
N/A
It is not required, but it will lighten GitHub executions
Not tested, just following GitHub docs.

ci: [+] github actions concurrency

---

build.sbt

Sbt now accepts only one single parameter for the spark version, if it is 3.x it will use the lates fix version, if is settled to 3.x.x will use exactly that version
#159 
Simplify the selection of spark version.
Run with multiple versions

Single parameter sparkVersion allows 3.x and 3.x.x versions

---

.github/actions/check_build_and_doc/action.yml
.github/actions/clean_cache/action.yml
.github/actions/publish_doc/action.yml
.github/workflows/ci.yml
.github/workflows/publishTempSite.yml
.github/workflows/release.yml

ci: [+] compose actions (issue #152)

---

.github/actions/check_build_and_doc/action.yml
.github/codecov.yml
README.md

Adding flag management for codecov reports
None
It doesn't seem right at codecov after adding flags: I couldn't see any flags at main and some files went missing
Not tested

fix: [~] codecov reports with flags

---

core/src/main/scala/doric/syntax/Interpolators.scala
core/src/test/scala/doric/syntax/InterpolatorsSpec.scala

Using `concat_ws` instead of `concat` we can avoid this error (but we have as limitation that nulls will be skipped)
Resolves #191

fix: [~] str interpolator now prints empty if null column (issue #191)

---

build.sbt
core/src/main/scala/doric/CName.scala
core/src/main/scala/doric/doric.scala

Delete unused dependencies to be able to port doric to scala 2.11
Deleted unused spark daria, and newtype that it doesn't have a 2.11 version
#205 
Make possible to build doric for scala 2.11
Against latest version of spark and waiting for the CI flow

Delete unused dependencies to be able to port doric to scala 2.11

---

build.sbt
core/src/main/scala/doric/DoricColumn.scala
core/src/main/scala/doric/DoricJoinColumn.scala
core/src/main/scala/doric/JoinSideDoricColumn.scala
core/src/main/scala/doric/sem/TransformOps.scala
core/src/main/scala/doric/syntax/AggregationColumns.scala
core/src/main/scala/doric/syntax/BinaryColumns.scala
core/src/main/scala/doric/syntax/StringColumns.scala
core/src/main/scala/doric/syntax/TimestampColumns.scala
core/src/main/scala/doric/syntax/TypeMatcher.scala
core/src/main/scala/doric/syntax/WhenBuilder.scala
core/src/main/scala/org/apache/spark/sql/doric/RelationalGroupedDatasetDoricInterface.scala
core/src/main/spark_3.0_3.1/scala/doric/syntax/BinaryColumns30_31.scala
core/src/main/spark_3.2/scala/doric/syntax/BinaryColumns32.scala

Cats imports fixed
Sbt prepared for 2.4 version
Cats for version 2.0.0 works if the imports are correct
#205 
#184 
Changed the dependency  version all test pass in 2.12 at least

Cats imports fixed

---

core/src/test/scala/doric/control/WhenBuilderSpec.scala
core/src/test/scala/doric/sem/JoinOpsSpec.scala

Poltergeist in publishLocal of 2.4
👻 
#205 
We want to publish!!!
publishLocal runs in spark 2.4 scala 2.11 version

Fixed publishLocal errors in test

---

core/src/main/scala/doric/DoricColumn.scala
core/src/main/scala/doric/doric.scala
core/src/main/scala/doric/syntax/ColGetters.scala
core/src/main/scala/doric/syntax/DStructs.scala
core/src/test/scala/doric/syntax/DStructOpsSpec.scala
core/src/test/scala/doric/syntax/DynamicSpec.scala
docs/docs/docs/api.md
docs/docs/docs/implicits.md
docs/docs/docs/quickstart.md

Implements #210.
@alfonsorr @eruizalo please, review

Dynamic invocations for `Row` columns and top row

---

.github/labeler.yml

Labeler now labels all spark versions when updating common/core code
N/A
https://github.com/eruizalo/doric/pull/4

feat: [~] label all sparks if doric core modified

---

core/src/main/scala/doric/sem/Errors.scala
core/src/test/scala/doric/matchers/CustomMatchers.scala
core/src/test/scala/doric/matchers/CustomMatchersSpec.scala
core/src/test/scala/doric/sem/ErrorsSpec.scala

Improved the message we show skipping the same error multiple times

Doric error message now doesn't show the same error multiple times.

---

core/src/main/scala/doric/sem/All.scala
core/src/main/scala/doric/sem/SortingOps.scala
core/src/main/scala/doric/syntax/CommonColumns.scala
core/src/test/scala/doric/sem/SortingOpsSpec.scala
core/src/test/scala/doric/syntax/CommonColumnsSpec.scala
core/src/test/scala/doric/syntax/DateColumnsSpec.scala
core/src/test/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/DateColumns3xSpec.scala

This PR is implements the `asc` and `desc` functions alongside the `orderBy` and `sort` functions currently present in Spark. 
Resolves https://github.com/hablapps/doric/issues/70
Currently when performing `orderBy` or sort operations in a DataFrame, you have to use Spark columns and functions. This PR aims to allow the use of doric columns when sorting.

Added Sorting Functions

---

.github/workflows/dependency-graph.yml

Improve dependency security with an action.
The action added updates the dependency graph of github to check any issues with the dependencies used
Closes #253

Added sbt-dependency-submission to update github dependency graph

---

.github/labeler.yml
core/src/main/scala/doric/syntax/NumericColumns.scala
core/src/main/spark_2.4_3.0_3.1/scala/doric/syntax/NumericColumns2_31.scala
core/src/main/spark_3.2_3.3/scala/doric/syntax/NumericColumns32.scala
core/src/test/scala/doric/Equalities.scala
core/src/test/scala/doric/TypedColumnTest.scala
core/src/test/scala/doric/syntax/AggregationColumnsSpec.scala
core/src/test/scala/doric/syntax/NumericOperationsSpec.scala
core/src/test/scala/doric/syntax/NumericUtilsSpec.scala
core/src/test/spark_3.1_3.2_3.3/scala/doric/syntax/Numeric31Spec.scala

* add the remaining non-aggregate functions
* a small ci change to autotag `project/build.properties` changes as a dependency PR
* Resolves #68 
- YES

feat: [+] remaining non aggregate functions (resolves #68)

---

core/src/main/scala/doric/syntax/ArrayColumns.scala
core/src/test/scala/doric/syntax/ArrayColumnsSpec.scala

Empty arrays contains a inner datatype of null instead of the type provided in doric, this can create inconsistencies checking the typing and not be what is expected.
* Resolves #273 
Tests to check the type when the array is empty
- YES

Empty arrays returns the expected datatype

---

core/src/main/scala/doric/syntax/ArrayColumns.scala
core/src/main/scala/doric/syntax/NumericColumns.scala
core/src/main/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/ArrayColumns3x.scala
core/src/test/scala/doric/SparkAuxFunctions.scala
core/src/test/scala/doric/syntax/ArrayColumnsSpec.scala
core/src/test/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/ArrayColumns3xSpec.scala

- [**feat**] ⬆️ array `sort` function with a lambda of two params. Now we provide an api not available until spark 3.4 (only available through sql expressions).
- [**feat**] ⬆️ array `sort` function with a lambda of one param. I have to thank @alfonsorr for this one, as it is his own idea, implementation. This functions is not available in any version of spark (yet).
- [**fix**] 😳💣 !**BREAKING_CHANGE**: ⚠️  `filterWIndex` from now on will be only available for spark 3.0+ (we have being testing this function only for spark 3.0+ and the filter function for spark 2.4 does not allow a lambda with 2 variables, so it would fail)
- [**fix**] 😳 `exists` array function have being tested only for spark 3.0+, but it is available for all spark versions. Now it will be tested for all versions
- …

feat: [+] #270 array_sort functions working with lambdas

---

core/src/main/scala/doric/syntax/BooleanColumns.scala
core/src/main/scala/doric/syntax/NumericColumns.scala
core/src/test/scala/doric/syntax/BooleanColumnsSpec.scala
core/src/test/scala/doric/syntax/NumericOperationsSpec.scala

Unary functions:
* Add minus(-) for numeric columns
* Fix not(!) for boolean columns
* Resolves #271 
- YES

feat: [+] #271 unary functions (-) & (!)

---

core/src/main/spark_3.1_3.2_3.3/scala/doric/syntax/StringColumns31.scala
core/src/test/spark_3.1_3.2_3.3/scala/doric/syntax/StringColumns31Spec.scala

raiseError function could be improved adding the column location on the error message
* Partially resolves #105
- YES

feat: [+] #105 improve raiseError with location

---

.github/actions/publish_doc/action.yml
.github/workflows/wc_publishSite.yml

From some time ago, github pages have been failing due to lack of permissions to push git changes. With this now it should work correctly.
* Resolves N/A
This has been tested creating this branch from doric repo and pushing this changes to see if this solves the issue:
- publish: https://github.com/hablapps/doric/actions/runs/3312323940
- build & deployment: https://github.com/hablapps/doric/actions/runs/3312354664
It has also been tested in my fork:
- publish: https://github.com/eruizalo/doric/actions/runs/3312368228
- build & deployment: https://github.com/eruizalo/doric/actions/runs/3312399353

fix: [~] gh-pages publish failing using git

---

core/src/main/scala/doric/doric.scala
core/src/main/scala/doric/syntax/AggregationColumns.scala
core/src/main/spark_3.2_3.3/scala/doric/sqlExpressions/CustomAgg.scala
core/src/main/spark_3.2_3.3/scala/doric/syntax/AggregationColumns32.scala
core/src/main/spark_3.2_mount/scala/doric/syntax/All.scala
core/src/main/spark_3.3_mount/scala/doric/syntax/All.scala
core/src/test/spark_3.2_3.3/scala/doric/syntax/AggregationColumns32Spec.scala
docs/docs/_data/navigation.yml
docs/docs/docs/exclusive.md
docs/src/main/scala/doric/AggExample.scala

This pull request allows the creation of aggregation functions with the syntax of doric.
Example of mean implemented with `customAgg` in doric
```scala
val complexAggWithoutNames = customAgg[Long, Row, Double](
col[Long]("id"),
struct(lit(0L), lit(0L)),
(x, y) =>
struct(
x.getChild[Long]("col1") + y,
x.getChild[Long]("col2") + 1L.lit
),
(x, y) =>
struct(
x.getChild[Long]("col1") + y.getChild[Long]("col1"),
x.getChild[Long]("col2") + y.getChild[Long]("col2")
),
x => x.getChild[Long]("col1") / x.getChild[Long]("col2")
)
```
* Resolves #311 
* Depends on XXX
The test is developed with simple and complex zero values.
- This pull request contains the appropriate tests?:
- YES

Custom aggregation with doric syntax

---

core/src/main/scala/doric/DoricColumn.scala
core/src/main/scala/doric/syntax/DStructs.scala
core/src/test/scala/doric/syntax/DynamicSpec.scala

Explained in the issue
* Resolves #265 
- YES

fix: [~] child dynamic accessor only for struct columns (issue #265)

---

.github/workflows/on_push_dev.yml

Dependabot was failing at `publish_doc` workflow:
> Starting March 1st, 2021 workflow runs that are triggered by Dependabot from push, pull_request, pull_request_review, or pull_request_review_comment events will be treated as if they were opened from a repository fork. This means they will receive a read-only GITHUB_TOKEN and will not have access to any secrets available in the repository. This will cause any workflows that attempt to write to the repository to fail.
> 
> This change will affect all repositories, both public and private, regardless of how they are configured, and is being made to prevent potentially compromised dependencies from capturing secrets referenced in your workflows.
Because of this we decided to disable the `publish_doc` workflows for these branches. It should …

ci: [~] dependabot now will never execute publish doc

---

core/src/main/scala/doric/CNameOrd.scala
core/src/main/scala/doric/syntax/CommonColumns.scala
core/src/main/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/ArrayColumns3x.scala
core/src/test/scala/doric/DoricColumnSpec.scala
core/src/test/scala/doric/syntax/CommonColumnsSpec.scala
core/src/test/scala/doric/syntax/DStructOpsSpec.scala
core/src/test/scala/doric/syntax/DynamicSpec.scala
core/src/test/scala/doric/testUtilities/data/User.scala
core/src/test/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/ArrayColumns3xSpec.scala
docs/docs/docs/exclusive.md
docs/docs/docs/implicits.md

This PR contains two new functions for doric:
* **Equals null safe**: `<=>`
* *Sort arrays for structs*: `colArray[Row]("value").sortBy(CName("name"), CNameOrd("age", Desc))` is available instead of createng ad-hoc sort functions or using ad-hoc expressions like:
```
f.expr("array_sort(value, (l, r) -> case " +
// name ASC
"when l.name < r.name then -1 " +
"when l.name > r.name then 1 " +
"else ( case" +
// age DESC
"  when l.age > r.age then -1 " +
"  when l.age < r.age then 1 " +
"  else 0 end " +
") end)"
)
```
* Resolves #337 
- YES

feat: [+] #337 array_sort of structs & equals null safe functions

---

core/src/main/scala/doric/syntax/AggregationColumns.scala
core/src/main/scala/doric/syntax/ControlStructures.scala
core/src/main/scala/doric/syntax/WhenBuilder.scala
core/src/test/scala/doric/TypedColumnTest.scala
core/src/test/scala/doric/control/WhenBuilderSpec.scala
core/src/test/scala/doric/syntax/AggregationColumnsSpec.scala
docs/docs/docs/exclusive.md

* `AND` / `OR` aggregate functions were added (equivalent to `min` and `max` respectively, but seems more clear this way)
* `WhenBuilder` for columns, very similar to `WhenBuilder`, intended to do a sequence of comparisons with the column itself. It looks like this:
```
colInt("c1").matches[String]
.caseW(_ > lit(10), "MAX".lit) // using a "compare" function
.caseW(lit(8), "Eight".lit).   // this is direct comparison between both columns (the very same as ==)
.otherwiseNull
```
* Resolves N/A
- YES

feat: [+] MatchBuilder column fun & AND/OR aggregate functions

---

build.sbt
core/src/main/scala/doric/DoricColumn.scala
core/src/main/scala/doric/syntax/ArrayColumns.scala
core/src/main/scala/doric/syntax/CommonColumns.scala
core/src/main/scala/doric/syntax/DStructs.scala
core/src/main/scala/doric/syntax/MapColumns.scala
core/src/main/scala/doric/syntax/StringColumns.scala
core/src/main/spark_2.4_mount/scala/doric/syntax/StringColumn24.scala
core/src/main/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/DStructs3x.scala
core/src/main/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/MapColumns3x.scala
core/src/main/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/StringColumn3x.scala
core/src/main/spark_3.0_mount/scala/doric/syntax/All.scala
core/src/main/spark_3.1_mount/scala/doric/syntax/All.scala
core/src/main/spark_3.2_mount/scala/doric/syntax/All.scala
core/src/main/spark_3.3_mount/scala/doric/syntax/All.scala
core/src/test/scala/doric/TypedColumnTest.scala
core/src/test/scala/doric/syntax/ArrayColumnsSpec.scala
core/src/test/scala/doric/syntax/DStructOpsSpec.scala
core/src/test/scala/doric/syntax/MapColumnsSpec.scala
core/src/test/scala/doric/syntax/StringColumnsSpec.scala
core/src/test/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/ArrayColumns3xSpec.scala
core/src/test/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/DStructs3xSpec.scala
core/src/test/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/MapColumns3xSpec.scala
core/src/test/spark_3.0_3.1_3.2_3.3/scala/doric/syntax/StringColumns3xSpec.scala
docs/docs/docs/exclusive.md

New collection & struct functions
:warning::warning: DO NOT MERGE UNTIL TODOS RESOLUTION :warning::warning:
* Resolves #64 
- YES

feat: [+] collection functions (issue #64)

---

core/src/main/scala/doric/syntax/StringColumns.scala
core/src/test/scala/doric/syntax/StringColumnsSpec.scala

This PR adds the following comparison operators to String columns: `<`, `<=`, `>` and `>=`. 
Whilst I'm touching parts like this if there are any other comparison operators for other types then please let me know, I'm more than happy to add them.
* Resolves https://github.com/hablapps/doric/issues/272
- YES 
- New unit tests added for each comparison operator

Issue-272: Add String Comparison operators

---

core/src/main/scala/doric/sem/TransformOps.scala
core/src/test/scala/doric/sem/TransformOpsSpec.scala

This PR updates `transform` ops to add the `drop` column found in Spark. The doric function has the following extra functionality:
- It will return an error if the column is not found in the DataFrame
- You can drop multiple columns using the `col` syntax
* Resolves [363](https://github.com/hablapps/doric/issues/363)
Unit tests have been updated to include testing of both `drop` functions.
- YES

ISSUE-363: Add the ability to Drop columns with DoricColumns

---

build.sbt
core/src/main/scala/doric/syntax/DStructs.scala

Newer versions of scala test requires an updated version of scala 2.13
#427 
* Resolves #427 
* Depends on none
Pass the provided test test is enough.
- YES

Update scala 2.13 to allow update dependencies
