- src/main/scala/habla/doric/FromDf.scala
- src/main/scala/habla/doric/doric.scala
- src/main/scala/habla/doric/syntax/DStructOps.scala
- src/main/scala/habla/doric/syntax/FromDfExtras.scala
- src/test/scala/habla/doric/DoricColumnsSpec.scala
- src/test/scala/habla/doric/syntax/DStructOpsSpec.scala
Implemented a struct dynamic typed
> Struct column

- src/main/scala/habla/doric/Casting.scala
- src/main/scala/habla/doric/Errors.scala
- src/main/scala/habla/doric/SparkType.scala
- src/main/scala/habla/doric/UnsafeCasting.scala
- src/main/scala/habla/doric/doric.scala
- src/main/scala/habla/doric/functions/WhenBuilder.scala
- src/main/scala/habla/doric/syntax/AllSyntax.scala
- src/main/scala/habla/doric/syntax/BooleanOperations.scala
- src/main/scala/habla/doric/syntax/ColumnExtractors.scala
- src/main/scala/habla/doric/syntax/CommonColumnOps.scala
- src/main/scala/habla/doric/syntax/DStructOps.scala
- src/main/scala/habla/doric/syntax/DataFrameOps.scala
- src/main/scala/habla/doric/syntax/NumericOperations.scala
- src/main/scala/habla/doric/types/DoricArrayType.scala
- src/main/scala/habla/doric/types/DoricBooleanType.scala
- src/main/scala/habla/doric/types/DoricDStructType.scala
- src/main/scala/habla/doric/types/DoricDateType.scala
- src/main/scala/habla/doric/types/DoricDoubleType.scala
- src/main/scala/habla/doric/types/DoricFloatType.scala
- src/main/scala/habla/doric/types/DoricInstantType.scala
- src/main/scala/habla/doric/types/DoricIntegerType.scala
- src/main/scala/habla/doric/types/DoricLongType.scala
- src/main/scala/habla/doric/types/DoricMapType.scala
- src/main/scala/habla/doric/types/DoricStringType.scala
- src/main/scala/habla/doric/types/DoricTimestampType.scala
- src/test/scala/habla/doric/DoricColumnsSpec.scala
- src/test/scala/habla/doric/TypedColumnTest.scala
- src/test/scala/habla/doric/syntax/DataFrameOpsSpec.scala
- src/test/scala/habla/doric/syntax/NumericOperationsSpec.scala
Also:
* Renaming of some classes (mainly FromDF to SparkType)
* Casting now skips the casting is to the same spark type
> Improved join error message

- .github/workflows/ci.yml
- .github/workflows/release.yml
Prevent CI worflow in main branch before merge and releases if not code is changed.
Also deleted useless matrix strategy
> Update workflows versions

- src/main/scala/habla/doric/DoricColumn.scala
- src/main/scala/habla/doric/Errors.scala
- src/main/scala/habla/doric/SparkType.scala
- src/main/scala/habla/doric/UnsafeCasting.scala
- src/main/scala/habla/doric/doric.scala
- src/main/scala/habla/doric/syntax/ColumnExtractors.scala
- src/main/scala/habla/doric/syntax/DataFrameOps.scala
> fix join errors message

- src/main/scala/doric/sem/DataFrameOps.scala
- src/main/scala/doric/sem/Errors.scala
- src/main/scala/doric/syntax/All.scala
- src/main/scala/doric/syntax/ColGetters.scala
- src/main/scala/doric/syntax/ControlStructures.scala
- src/main/scala/doric/syntax/WhenBuilder.scala
- src/main/scala/doric/types/NumericType.scala
- src/main/scala/doric/types/SparkType.scala
> * Pachage splitting

- core/src/main/scala/doric/doric.scala
- core/src/main/scala/doric/syntax/All.scala
- core/src/main/scala/doric/syntax/BinaryColumns.scala
- core/src/main/scala/doric/syntax/BooleanColumns.scala
- core/src/main/scala/doric/syntax/ColGetters.scala
- core/src/main/scala/doric/syntax/CommonColumns.scala
- core/src/main/scala/doric/syntax/DateColumns.scala
- core/src/main/scala/doric/syntax/NumericColumns.scala
- core/src/main/scala/doric/syntax/StringColumns.scala
- core/src/main/scala/doric/syntax/TimestampColumns.scala
- core/src/main/scala/doric/syntax/WhenBuilder.scala
- core/src/main/scala/doric/types/BinaryType.scala
- core/src/main/scala/doric/types/Casting.scala
- core/src/main/scala/doric/types/SparkType.scala
- core/src/test/scala/doric/TypedColumnTest.scala
- core/src/test/scala/doric/syntax/BinaryColumnsSpec.scala
- core/src/test/scala/doric/syntax/BooleanColumnsSpec.scala
- core/src/test/scala/doric/syntax/CommonColumnsSpec.scala
- core/src/test/scala/doric/syntax/DateColumnsSpec.scala
- core/src/test/scala/doric/syntax/NumericOperationsSpec.scala
- core/src/test/scala/doric/syntax/StringColumnsSpec.scala
- core/src/test/scala/doric/syntax/TimestampColumnsSpec.scala
* feat: Date time functions #65
* feat: String functions #71
* feat: Misc functions resolves #67
* feat: Binary column resolves #103
* feat: NullColumn & refactor
> new columns and functions

- .github/workflows/release.yml
> Revert "ci: release executed only if habla repository"

- .github/labeler.yml
- .github/workflows/labeler.yml
After this changes are in main, pull request will be auto-tagged
> ci: [+] PR labeler

- .github/labeler.yml
Update labeler workflow adding spark labels
N/A
This is supposed to add corresponding spark labels depending on the modifications
Not tested
> ci: [+] add spark labels to labeler

- .github/dependabot.yml
- .github/workflows/publishTempSite.yml
- .github/workflows/release.yml
- .scala-steward.conf
- README.md
- build.sbt
- docs/docs/docs/quickstart.md
* fix: [~] publish temp site will ignore main branch in order to avoid publish twice when merging (release workflow also publish)
* ci: [~] change release number from 0.0.2 to 0.0.3
* ci: [+] dependabot pull requests enhanced
* ci: [-] scala-steward
* should ignore spark-sql updates
* PRs enhancement
There is no linked issue
No tests could be done
> feat_fix: [~] Prepare release 0.0.3 & other fixes

- .github/actions/check_build_and_doc/action.yml
Artifact paths are not working
> Fix artifact upload

- README.md
- build.sbt
- docs/docs/docs/api.md
- docs/docs/docs/quickstart.md
All documentation updated for version 0.0.4
> Ready for version 0.0.4

- .github/workflows/release.yml
The action attaches the jars to the release page in GH.
Better way to find the jars in the project.
> Action to add the packages to the release page in gh

- .github/pull_request_template.md
- .github/workflows/ci.yml
New GitHub Action which enforces PR dependencies as stated in a PR's opening comment. --> https://github.com/marketplace/actions/pr-dependency-check
N/A
Tested via PR actions
> ci: [+] PR Dependency Check

- README.md
- build.sbt
- docs/docs/docs/quickstart.md
Update to the new published version the documentation
- No need to test
> Updated documentation references

- .github/ISSUE_TEMPLATE/bug_report_form.yml
- .github/ISSUE_TEMPLATE/feature_request_form.yml
It seems dropdown yml types are not working correctly, making forms not to show when you create a new issue (https://github.com/hablapps/doric/issues/new/choose)
This is what we see now:
This is what we should see instead:
* Resolves N/A
- YES
- They showed up again in my private repo after this changes
> fix: [~] issues & feature requests forms

- .github/workflows/pr_comment.yml
Just a dump to know github context and know why we are not taking the PR number.
Related to #284
> debug: github context dump PR comment

- .scala-steward.conf
> Skip scoverage in scala steward

- .github/workflows/release.yml
Maven release job was failing due to concurrency problems, with this new configuration `mvn_release` job will run sequentially.
* Resolves N/A
- NO
- As it is related to hablapps workspace, only when releasing and uploading to maven it cannot be tested, but I tested this functionality in a different repo
> feat: [+] mvn release sequential

- README.md
- build.sbt
- docs/docs/docs/quickstart.md
Update all links and versions to 0.0.6
> Update references to 0.0.6

- .github/workflows/matrix_includes.json
- build.sbt
- docs/docs/docs/api.md
- docs/docs/docs/quickstart.md
Add spark 3.3.2
* Resolves #329 
- YES
> feat: [+] #329 add spark 3.3.2

- core/src/test/scala/doric/syntax/AggregationColumnsSpec.scala
Pull request #336 auto-merged unexpectedly having some errors, this PR delete some tests of previously deleted functions
* Resolves N/A
- N/A
> hotfix: [-] delete auto-merged tests that should not be there

- README.md
- build.sbt
Update documentation and readme with version 0.0.7 as the default version
> Documentation update to show new version

- docs/docs/_data/navigation.yml
> Fix link for doric exlusive features

- build.sbt
Update scala 2.13 to version 14
#448 cant update without newer version of scala 2.13
CI has to pass
- YES
> Update scala 2.13 version

- .github/workflows/release.yml
The plugin to upload files to gh is deprecated.
> Deleted CI plugin

- .github/workflows/ci.yml
- .github/workflows/wc_publishSite.yml
- build.sbt
- project/plugins.sbt
Fix scoverage dependency
* Resolves XXX
* Depends on XXX
- YES / NO
- Something relevant to mention
> Fix microsite error.
